/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'Novelty' : IDL.Null,
  'Bombs' : IDL.Null,
  'Sparklers' : IDL.Null,
  'FlowerPots' : IDL.Null,
  'GroundChakkar' : IDL.Null,
  'AerialShots' : IDL.Null,
  'Rockets' : IDL.Null,
});
export const ProductId = IDL.Nat;
export const Product = IDL.Record({
  'id' : ProductId,
  'inStock' : IDL.Bool,
  'packSize' : IDL.Text,
  'name' : IDL.Text,
  'minAge' : IDL.Nat,
  'description' : IDL.Text,
  'effectDuration' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : Category,
  'safetyRating' : IDL.Nat,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        Category,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Bool,
      ],
      [ProductId],
      [],
    ),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'listByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'listInStock' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'Novelty' : IDL.Null,
    'Bombs' : IDL.Null,
    'Sparklers' : IDL.Null,
    'FlowerPots' : IDL.Null,
    'GroundChakkar' : IDL.Null,
    'AerialShots' : IDL.Null,
    'Rockets' : IDL.Null,
  });
  const ProductId = IDL.Nat;
  const Product = IDL.Record({
    'id' : ProductId,
    'inStock' : IDL.Bool,
    'packSize' : IDL.Text,
    'name' : IDL.Text,
    'minAge' : IDL.Nat,
    'description' : IDL.Text,
    'effectDuration' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : Category,
    'safetyRating' : IDL.Nat,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          Category,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Bool,
        ],
        [ProductId],
        [],
      ),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'listByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
    'listInStock' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };